# Module 2: AI problem solving


____

### Reading and reflection


Read the papers "The Netflix Prize Download The Netflix Prize" and "Lessons from the Netflix Prize Challenge Download Lessons from the Netflix Prize Challenge" and write a half-page summary of your take-aways from them. Pick two design features (e.g., regarding data, models, algorithms) that characterise the task and the solution in the papers and discuss how they may differ in another application of recommendation systems.

## Implementation

In [2]:
import numpy as np
import pandas as pd
import sklearn

In [3]:
user_reviews = pd.read_csv('user_reviews.csv')
movie_genres = pd.read_csv('movie_genres.csv')

In [4]:
user_reviews_copy = user_reviews.copy()
movie_genres_copy = movie_genres.copy()

In [5]:
user_reviews_copy.head()

,Unnamed: 0,User,The Net,Happily N'Ever After,Tomorrowland,American Hero,Das Boot,Final Destination 3,Licence to Kill,The Hundred-Foot Journey,...,The Martian,Micmacs,Solomon and Sheba,In the Company of Men,Silent House,Big Fish,Get Real,Trading Places,DOA: Dead or Alive,Hey Arnold! The Movie
0,0,Vincent,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,Edgar,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,Addilyn,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,Marlee,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,Javier,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
movie_genres_copy.head()

,Unnamed: 0,movie_title,genre_action,genre_adventure,genre_animation,genre_biography,genre_comedy,genre_crime,genre_documentary,genre_drama,...,genre_mystery,genre_news,genre_reality-tv,genre_romance,genre_sci-fi,genre_short,genre_sport,genre_thriller,genre_war,genre_western
0,0,The Net,1,0,0,0,0,1,0,1,...,1,0,0,0,0,0,0,1,0,0
1,1,Happily N'Ever After,0,1,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,Tomorrowland,1,1,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
3,3,American Hero,1,0,0,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,0
4,4,Das Boot,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,1,0

In [7]:
movie_genres_copy = movie_genres_copy.set_index('movie_title').drop('Unnamed: 0', axis=1)

movie_genres_copy.head()

,genre_action,genre_adventure,genre_animation,genre_biography,genre_comedy,genre_crime,genre_documentary,genre_drama,genre_family,genre_fantasy,...,genre_mystery,genre_news,genre_reality-tv,genre_romance,genre_sci-fi,genre_short,genre_sport,genre_thriller,genre_war,genre_western
movie_title,,,,,,,,,,,,,,,,,,,,,
The Net,1,0,0,0,0,1,0,1,0,0,...,1,0,0,0,0,0,0,1,0,0
Happily N'Ever After,0,1,1,0,1,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
Tomorrowland,1,1,0,0,0,0,0,0,1,0,...,1,0,0,0,1,0,0,0,0,0
American Hero,1,0,0,0,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
Das Boot,0,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,1,0

### Content based filtering (Mathematical approach, no model)

By calculating the average genre profile for a user based on the movies they rated

In [14]:
'''
def get_film_genres(genres_df, film_idx) -> list:
    
    genres = genres_df.iloc[film_idx, 2:]

    genres = genres[genres == 1]

    return genres.index.tolist()
'''


def user_profile(reviews_df, genres_df, user_idx) -> pd.Series:

    #name = reviews_df.iloc[user_idx, 1]

    reviews = reviews_df.iloc[user_idx, 2:]

    rated_movies = reviews[reviews != 0]
    unrated_movies = reviews[reviews == 0]

    genres_rated_movies = genres_df.loc[rated_movies.index]
    genres_unrated_movies = genres_df.loc[unrated_movies.index]

    
    profile = genres_rated_movies.T.dot(rated_movies)
    profile /= profile.sum() #normalize
    print(profile)

    similarity_score = genres_unrated_movies.dot(profile)
    return similarity_score

In [15]:
#Vincent
user_profile(user_reviews_copy, movie_genres_copy, 0)

genre_action          51.0
genre_adventure       26.0
genre_animation        3.0
genre_biography        8.0
genre_comedy          35.0
genre_crime           17.0
genre_documentary      0.0
genre_drama          120.0
genre_family           3.0
genre_fantasy         29.0
genre_film-noir        0.0
genre_history          3.0
genre_horror           5.0
genre_music            9.0
genre_musical          5.0
genre_mystery         14.0
genre_news             0.0
genre_reality-tv       0.0
genre_romance         58.0
genre_sci-fi          18.0
genre_short            0.0
genre_sport            3.0
genre_thriller        45.0
genre_war              3.0
genre_western          0.0
dtype: object

The Net                  0.542857
Happily N'Ever After     0.210989
Tomorrowland             0.246154
American Hero            0.492308
Das Boot                 0.426374
                           ...
Big Fish                 0.384615
Get Real                 0.468132
Trading Places           0.076923
DOA: Dead or Alive       0.169231
Hey Arnold! The Movie    0.147253
Length: 1961, dtype: object

In [16]:
users = ['Vincent', 'Edgar', 'Addilyn', 'Marlee', 'Javier']

for i, user in enumerate(users):

    user_scores = user_profile(user_reviews_copy, movie_genres_copy, i)

    recommended_movies = user_scores.sort_values(ascending=False).head(5)

    recommended_movies = recommended_movies.index.tolist()

    print(f'Movie recommendations for {user}:\n {recommended_movies}\n')

genre_action          51.0
genre_adventure       26.0
genre_animation        3.0
genre_biography        8.0
genre_comedy          35.0
genre_crime           17.0
genre_documentary      0.0
genre_drama          120.0
genre_family           3.0
genre_fantasy         29.0
genre_film-noir        0.0
genre_history          3.0
genre_horror           5.0
genre_music            9.0
genre_musical          5.0
genre_mystery         14.0
genre_news             0.0
genre_reality-tv       0.0
genre_romance         58.0
genre_sci-fi          18.0
genre_short            0.0
genre_sport            3.0
genre_thriller        45.0
genre_war              3.0
genre_western          0.0
dtype: object
Movie recommendations for Vincent:
 ["Perrier's Bounty", 'Alpha and Omega 4: The Legend of the Saw Toothed Cave', 'El Mariachi', 'Nowhere to Run', 'The Good Thief']

genre_action         12.0
genre_adventure      11.0
genre_animation       9.0
genre_biography       3.0
genre_comedy         22.0
genre_crime          18.0
genre_documentary     5.0
genre_drama          87.0
genre_family          4.0
genre_fantasy        14.0
genre_film-noir       0.0
genre_history         5.0
genre_horror         10.0
genre_music           7.0
genre_musical        15.0
genre_mystery         8.0
genre_news            0.0
genre_reality-tv      0.0
genre_romance        34.0
genre_sci-fi         16.0
genre_short           0.0
genre_sport           5.0
genre_thriller       31.0
genre_war            10.0
genre_western         5.0
dtype: object
Movie recommendations for Edgar:
 ["Perrier's Bounty", 'The Hunting Party', 'Harvard Man', 'Alpha and Omega 4: The Legend of the Saw Toothed Cave', 'West Side Story']

genre_action         23.0
genre_adventure      24.0
genre_animation      10.0
genre_biography       6.0
genre_comedy         93.0
genre_crime          26.0
genre_documentary     0.0
genre_drama          66.0
genre_family         18.0
genre_fantasy        23.0
genre_film-noir       0.0
genre_history         0.0
genre_horror         23.0
genre_music          15.0
genre_musical        10.0
genre_mystery         2.0
genre_news            0.0
genre_reality-tv      0.0
genre_romance        29.0
genre_sci-fi         15.0
genre_short           0.0
genre_sport           7.0
genre_thriller       31.0
genre_war             0.0
genre_western         0.0
dtype: object
Movie recommendations for Addilyn:
 ['Alpha and Omega 4: The Legend of the Saw Toothed Cave', "Perrier's Bounty", 'Sinbad: Legend of the Seven Seas', 'Lilo & Stitch', 'Harvard Man']

genre_action         18.0
genre_adventure      14.0
genre_animation       0.0
genre_biography       4.0
genre_comedy         44.0
genre_crime          27.0
genre_documentary     0.0
genre_drama          68.0
genre_family          8.0
genre_fantasy        10.0
genre_film-noir       0.0
genre_history         4.0
genre_horror         21.0
genre_music           4.0
genre_musical         0.0
genre_mystery        18.0
genre_news            0.0
genre_reality-tv      0.0
genre_romance        15.0
genre_sci-fi         14.0
genre_short           0.0
genre_sport           5.0
genre_thriller       45.0
genre_war             4.0
genre_western         4.0
dtype: object
Movie recommendations for Marlee:
 ["Perrier's Bounty", 'Alpha and Omega 4: The Legend of the Saw Toothed Cave', 'Cheap Thrills', 'Exit Wounds', 'The Glimmer Man']

genre_action         12.0
genre_adventure      20.0
genre_animation      24.0
genre_biography      10.0
genre_comedy         50.0
genre_crime           5.0
genre_documentary     0.0
genre_drama          44.0
genre_family         36.0
genre_fantasy        20.0
genre_film-noir       0.0
genre_history         0.0
genre_horror         13.0
genre_music           4.0
genre_musical         2.0
genre_mystery         5.0
genre_news            0.0
genre_reality-tv      0.0
genre_romance        10.0
genre_sci-fi          4.0
genre_short           0.0
genre_sport           4.0
genre_thriller       11.0
genre_war             4.0
genre_western         0.0
dtype: object
Movie recommendations for Javier:
 ['Alpha and Omega 4: The Legend of the Saw Toothed Cave', 'Sinbad: Legend of the Seven Seas', 'Lilo & Stitch', 'The Magic Sword: Quest for Camelot', 'Jonah: A VeggieTales Movie']

### Collaborative filtering